spring:
  datasource:
    username: postgres
    password: ENC(mJ70WkkY6RhvrENgnxlK1/rHMWLnATce92JCDrPsDoAblnXnwkekbnissWNp6qpGd/5EFSBx9zuAEx0BkKOvpUq4vC5ZRz5ZC7dGNJRBJDzKqQWsZVMGYSjYWUkl5csmNZQCdbfPrWhxkFfPr7Xjj2kxdyUTt60RAfeCSt4TrJoPkmR7C6BGHH7fiDkQ484SwJ6Sr0g9mkcdJKn7OeER1wMU4TeKZH0h0EKHON264GOYAetYW/P1VWiU0PyMyjxeYQ26HGdVelETThHwXewOB8Ke7Xk2qSpr78TJ/CMmhEBIDeMXU5wf0NysGr1wqUbja8d149It8o/gsbxbxn3OhQ==)
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    hikari:
      schema: public

jasypt:
  encryptor:
    privateKeyLocation: file:src/test/resources/certs/local/private.pem

server:
  ssl:
    key-store: src/test/resources/certs/local/localhost.p12
    key-store-password: ENC(sWOC63OmPlk8YzrT/M+o1nlpwiGn/5HwPQRUd4T1kobpzcFrCgLVm9uQpgvJGT6kB27oC2wwDdhTgPOhZ9NKPIveGf8q2qr+DwAgFlKYv2enGgZVYg6XzLG+Zg2bDVuwdAETVwSoMlDjdO30ijBo41DDTJLngVOzYMFiIXboB5vi//o5rwxjAYQwNWxPFTuSa3RZxCZ7SDpVQTcLyWIlu+29o12XuURIth3TaJFh1vhLaakBVvrqvhlQ/pK/2j8BBe6uDRGx/IlNq5Lz/6a+GHkyE6aH+gw5X0/CvRISmG3bHpjXRO2SIiIy+qtKN/EtYbAcodWqXgfi0/XzkuY2SQ==)
    key-alias: localhost
    key-password: ENC(sWOC63OmPlk8YzrT/M+o1nlpwiGn/5HwPQRUd4T1kobpzcFrCgLVm9uQpgvJGT6kB27oC2wwDdhTgPOhZ9NKPIveGf8q2qr+DwAgFlKYv2enGgZVYg6XzLG+Zg2bDVuwdAETVwSoMlDjdO30ijBo41DDTJLngVOzYMFiIXboB5vi//o5rwxjAYQwNWxPFTuSa3RZxCZ7SDpVQTcLyWIlu+29o12XuURIth3TaJFh1vhLaakBVvrqvhlQ/pK/2j8BBe6uDRGx/IlNq5Lz/6a+GHkyE6aH+gw5X0/CvRISmG3bHpjXRO2SIiIy+qtKN/EtYbAcodWqXgfi0/XzkuY2SQ==)
    trust-store: src/test/resources/certs/local/truststore.p12
    trust-store-password: ENC(sWOC63OmPlk8YzrT/M+o1nlpwiGn/5HwPQRUd4T1kobpzcFrCgLVm9uQpgvJGT6kB27oC2wwDdhTgPOhZ9NKPIveGf8q2qr+DwAgFlKYv2enGgZVYg6XzLG+Zg2bDVuwdAETVwSoMlDjdO30ijBo41DDTJLngVOzYMFiIXboB5vi//o5rwxjAYQwNWxPFTuSa3RZxCZ7SDpVQTcLyWIlu+29o12XuURIth3TaJFh1vhLaakBVvrqvhlQ/pK/2j8BBe6uDRGx/IlNq5Lz/6a+GHkyE6aH+gw5X0/CvRISmG3bHpjXRO2SIiIy+qtKN/EtYbAcodWqXgfi0/XzkuY2SQ==)
jwt:
  publicKey: file:src/test/resources/certs/local/public.pem
  privateKey: file:src/test/resources/certs/local/private.pem