spring:
  datasource:
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    url: ${JDBC_URL}
    driverClassName: ${JDBC_DRIVER}
    hikari:
      schema: ${JDBC_SCHEMA}
  flyway:
    baseline-on-migrate: true

jasypt:
  encryptor:
    privateKeyLocation: ${ENCRYPTOR_KEY}
    privateKeyFormat: PEM

server:
  port: 8443
  ssl:
    enabled: true
    client-auth: need
    key-store: ${KEYSTORE_LOCATION}
    key-store-password: ${KEYSTORE_PASSWORD}
    key-alias: ${KEY_ALIAS}
    key-password: ${KEY_PASSWORD}
    trust-store: ${TRUSTSTORE_LOCATION}
    trust-store-password: ${TRUSTSTORE_PASSWORD}
jwt:
  expirationInMillis: 1800000
  publicKey: ${JWT_PUBLIC_KEY}
  privateKey: ${JWT_PRIVATE_KEY}